linz/basemaps-config

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Adding `palmerston-north_urban_2018-2019_0-125m`
**EPSG:2193**
https://basemaps.linz.govt.nz/?i=01ESF5PJSKPV8JVA3E4MA96W5H&v=head&debug=true&p=2193#@-40.38731729,175.63053027,z8.6442
All Imagery: https://basemaps.linz.govt.nz/?v=pr-11&p=2193&debug=true#@-40.38731729,175.63053027,z8.6442
**EPSG:3857**
https://basemaps.linz.govt.nz/?i=01ESF5MHFP5RCKQW94Z2947CES&v=head&debug=true#@-40.32861751,175.65765567,z11.9747 
All Imagery: https://basemaps.linz.govt.nz/?v=pr-11&debug=true#@-40.32861751,175.65765567,z11.9747
=> feat(imagery/aerial): add Palmerston North urban 2018-2019

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Adds `waimate_urban_2018_0-075m_RGB`
**EPSG:3857**
https://basemaps.linz.govt.nz/?i=01ESF5HA3BXN5E50Z0608KJGTG&v=head&debug=true#@-44.7381474,171.07032214,z11.0294
All Aerial: https://basemaps.linz.govt.nz/?v=pr-10&debug=true#@-44.63374882,171.14429427,z11.4941
**EPSG:2193** 
https://basemaps.linz.govt.nz/?i=01ESF5GRYSF8FD8GJ8C5MBK8H4&p=2193&v=head&debug=true#@-44.73543572,171.16672083,z5.9987
All Aerial: https://basemaps.linz.govt.nz/?v=pr-10&debug=true&p=2193#@-44.63374882,171.14429427,z11.4941
=> feat(imagery/aerial): add Waimate urban 2018

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Porirua Urban 2020
**EPSG:2193 - NZTM**
`01ESJAYEBZ8WT8M81X6SB1F09W` - https://basemaps.linz.govt.nz/?i=01ESJAYEBZ8WT8M81X6SB1F09W&p=2193#@-41.10471315,174.86177486,z8.7767
`aerial` - https://basemaps.linz.govt.nz/?v=pr-12&p=2193#@-41.10471315,174.86177486,z8.7767
**EPSG:3857 - WebMercator**
`01ESM35CSPVJD54ZMT4T5FVV29` -https://basemaps.linz.govt.nz/?i=01ESM35CSPVJD54ZMT4T5FVV29&v=head#@-41.11433748,174.86209305,z12.1949
`aerial` - https://basemaps.linz.govt.nz/?v=pr-12#@-41.10471315,174.86177486,z14.323
Ref
https://github.com/linz/topo-roadmap/issues/17
=> feat(imagery/aerial): adding porirua_urban_2020_0.10m to aerial layer

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Hurunui Urban 2018-2019
id: 01ESPMM6AZW0GH43NRYD7ARR1M
https://basemaps.linz.govt.nz/?i=01ESPMM6AZW0GH43NRYD7ARR1M&v=head&debug=true&p=2193#@-42.81000461,173.19871741,z6.3459
aerial - https://basemaps.linz.govt.nz/?v=pr-13&p=2193#@-42.56077863,172.80310804,z9.1033
id: 01ESPMPK1H0CH2G5K839WN1BT9
https://basemaps.linz.govt.nz/?i=01ESPMPK1H0CH2G5K839WN1BT9&v=head&debug=true#@-42.87383585,173.13812338,z9.9734
aerial - https://basemaps.linz.govt.nz/?v=pr-13&p=2193#@-42.56077863,172.80310804,z9.1033
Ref
linz/topo-roadmap#19
=> feat(imagery/aerial): adding hurunui_urban_2018-2019_0.075m_RGB to aerial layer

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Selwyn Urban 2018-2019
id: 01ESPW1197CY4JXEMVES99GZFA
https://basemaps.linz.govt.nz/?i=01ESPW1197CY4JXEMVES99GZFA&v=head&debug=true&p=2193#@-43.56781819,172.04286922,z6.4089
aerial - https://basemaps.linz.govt.nz/?v=pr-14&p=2193#@-43.48527635,172.11765846,z11.8225
id: 01ESPVY6HBS1SH79ZH24RW7ZSQ
https://basemaps.linz.govt.nz/?i=01ESPVY6HBS1SH79ZH24RW7ZSQ&v=head&debug=true#@-43.50496578,172.11616193,z9.9985
aerial - https://basemaps.linz.govt.nz/?v=pr-14#@-43.60151651,172.37221051,z14.7161
Ref
linz/topo-roadmap#1
=> feat(imagery/aerial): adding Selwyn imagery selwyn_urban_2018-2019_0.075m_RGB to aerial layer

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
**These are still processing and should be ready in about 30minutes**
Christchurch urban (`christchurch_urban_2015-2016_0-075m_RGBA`) had a collection of giant white squares inside the imagery as some of the source imagery had not been processed into a transparent layer.
Vs the reprocessed
**EPSG:3857 - WebMercator** [01EWEQ26HDCMDQKTZ1RHSXPBEW](https://basemaps.linz.govt.nz/?i=01EWEQ26HDCMDQKTZ1RHSXPBEW&v=head#@-43.79524854,172.93885027,z13.4734) [aerial](https://basemaps.linz.govt.nz/?v=pr-16#@-43.79524854,172.93885027,z13.4734)
**EPSG:2193 - NZTM** [01EWEQ49T0SC2N4T1VXC8W2ZYS](https://basemaps.linz.govt.nz/?i=01EWEQ49T0SC2N4T1VXC8W2ZYS&v=head&p=2193#@-43.65859654,172.84111169,z6.3906) [aerial](https://basemaps.linz.govt.nz/?v=pr-16&p=2193#)
=> feat(imagery/aerial): adding new processed copy of christchurch_urban_2015-2016_0-075m

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Tasman Rural 2020
id: 01EXJVE1W1D93VA0PVD3T5TXB6
https://basemaps.linz.govt.nz/?i=01EXJVE1W1D93VA0PVD3T5TXB6&v=head&debug=true&p=2193#@-41.71757294,172.89603213,z9.8928
aerial - https://basemaps.linz.govt.nz/?v=pr-18&p=2193#@-41.71757294,172.89603213,z9.8928
id: 01EXJV4VZ22G163H5565R2D04R
https://basemaps.linz.govt.nz/?i=01EXJV4VZ22G163H5565R2D04R&v=head&debug=true#@-41.71757294,172.89603213,z9.8928
aerial - https://basemaps.linz.govt.nz/?v=pr-18#@-41.71757294,172.89603213,z9.8928
Ref
linz/topo-roadmap#30
=> feat(imagery/aerial): adding tasman_rural_2020_0.3m_RGB.

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Hawkes bay Rural 2020
id: 01EYH1E63CY2QJSVBM9GMT2E7H
imagery - https://basemaps.linz.govt.nz/?i=01EYH1E63CY2QJSVBM9GMT2E7H&v=head&debug=true&p=2193#@-39.74595895,176.50860833,z4.9545
pull request -  https://basemaps.linz.govt.nz/?v=pr-19&p=2193#@-39.74595895,176.50860833,z4.9545
id: 01EYH18XFNJM0E7WNYDVK9KGGD
imagery - https://basemaps.linz.govt.nz/?i=01EYH18XFNJM0E7WNYDVK9KGGD&v=head&debug=true#@-39.74193239,176.92391278,z8.6266
pull request - https://basemaps.linz.govt.nz/?v=pr-19#@-39.74193239,176.92391278,z8.6266
Ref
linz/topo-roadmap#31
=> feat(imagery/aerial): adding hawkes-bay_rural_2018-2019_0.3m_RGB

config/imagery/aerial-2193.json, config/imagery/aerial-3857.json
Gisborne bay Rural 2020
id: 01EZWZF16E9AH34KRXVGY4DN1C
imagery - https://basemaps.linz.govt.nz/?i=01EZWZF16E9AH34KRXVGY4DN1C&v=head&debug=true&p=2193#@-38.07428027,177.99312564,z7.2496
pull request - https://basemaps.linz.govt.nz/?v=pr-20&p=2193#@-38.07428027,177.99312564,z7.2496
id: 01EZWZGMW2Q53VNC65X2X4VFRZ
imagery - https://basemaps.linz.govt.nz/?i=01EZWZGMW2Q53VNC65X2X4VFRZ&v=head&debug=true#@-38.05410487,177.8364418,z9.1751
pull request - https://basemaps.linz.govt.nz/?v=pr-20#@-38.05410487,177.8364418,z9.1751
Ref
linz/topo-roadmap#36
=> feat(imagery/aerial): gisborne_rural_2017-2019_0.3m_RGB

config/imagery/aerial-2193.json
This switches the NZTM2000 gebco layer for one that has a greater area so that it works better in NZTM2000Quad
Gebco Layer
[2193](https://basemaps.linz.govt.nz/?p=2193&i=01F1BFJN8R8P7BXN3XTHC5MT5G&v=head#@-42.16233885,175.6359337,z2.1827)
[NZTM2000Quad](https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=01F1BFJN8R8P7BXN3XTHC5MT5G&v=head#@-38.50439414,174.70639941,z2.5952)
Aerial Layer
[2193](https://basemaps.linz.govt.nz/?v=pr-21&p=nztm2000#@-39.74595895,176.50860833,z4.9545)
[NZTM2000Quad](https://basemaps.linz.govt.nz/?v=pr-21&p=nztm2000quad#@-39.74595895,176.50860833,z4.9545)
Old Coverage area
New Coverage Aera
=> feat(imagery/aerial): add improved gebco for nztm2000quad

config/tileset/topographic.json
After some performance testing splitting the buckets between imagery and vector data has caused the number of initial TLS connection delays to double.
An initial TLS connection to S3 generally takes 200-300ms and every subsequent request generally 10-30ms. by using two buckets we doubled the number of initial TLS connections.
=> perf: use the same bucket for all of the assets

config/tileset/aerial.json, src/cli.import.config.ts
Massive increase in coverage after a new delivery of imagery.
EPSG:2193
id: 01FBGB1QN859XRGNNWT6ZBHEN8
https://basemaps.linz.govt.nz/?i=01FBGB1QN859XRGNNWT6ZBHEN8&p=nztm2000quad&debug=true#@-41.8020714,172.9271309,z6.9065
EPSG:3857
id: 01FBGB0T73562VAZBEBHZ7E84T
https://basemaps.linz.govt.nz/?i=01FBGB0T73562VAZBEBHZ7E84T&debug=true#@-41.7483813,172.6836625,z8.182
ref: linz/topo-roadmap#30
**Old imagery** - [Basemaps](https://basemaps.linz.govt.nz/?i=01EXJV4VZ22G163H5565R2D04R) - [2193](https://basemaps.linz.govt.nz/?i=01F6P1VP3MR21HRWWRXW0XC252&p=nztm2000quad)
**New imagery** - [Basemaps](https://basemaps.linz.govt.nz/?i=01FBGB0T73562VAZBEBHZ7E84T) - [2193](https://basemaps.linz.govt.nz/?i=01FBGB1QN859XRGNNWT6ZBHEN8&p=nztm2000quad)
=> feat(aerial): update tasman rural to new larger tasman rural

config/tileset/aerial.json
WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FC1Y20KQZQDJESGSR97G9SSW&debug=true#@-40.8697146,175.1265201,z10.2799
NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FC1XYXHBADGNDYM36SH8D1XY&p=NZTM2000Quad&debug=true#@-40.8689122,175.1528513,z8.5632
New Images
Old Images
=> feat(aerial): Import kapiti-coast_urban_2021_0.075m_RGB config into basemaps.

src/tileset.config.ts
add `.pdf` at the end of invalidate path seems not working very well and also we need to clear the cache for other format.
=> fix(scripts): remove the pbf after the invalidate path.

config/imagery/geographx_nz_dem_2012_8-0m-WebMercatorQuad.json, config/tileset/reliefshade.json
this was processed using bilinear resampling rather than lanczos as too much transparency was causing issues
=> feat(imagery): improved relief shade with better overview quality

config/style/basic.json
We do not use a transportation_name layer for our road names so get the names directly from the transportation layer
=> vector(basic): use the transportation layer for names

config/tileset/aerial.json
As discussed, we want to put this above the all the Auckland urban layers.
=> feat(aerial): Config auckland rural 2020 into basemaps.

.github/workflows/build.yml, bin/basemaps-config.js, bin/basemaps-job.js, bin/bmc.js, bin/import-fonts.js, bin/import-style.js, package.json, src/commands/fonts.ts, src/commands/import.ts, src/commands/job.ts, src/commands/style.ts, src/index.ts, tsconfig.json, yarn.lock
This moves all the CLIs into `bmc` eg to import fonts
`./bin/bmc.js fonts`
=> refactor(deps): move to oclif/core as oclif/command is deprecated

config/tileset/aerial.json
Imagery imported for ōtorohanga_urban_2021_0.1m_RGB, please use the following QA url once the aws job finished.
NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FYWKAJ86W9P7RWM1VB62KD0H&p=NZTM2000Quad&debug#@-38.112026,175.028521,z9
WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FYWKATAEK2ZTJQ2PX44Y0XNT&p=WebMercatorQuad&debug#@-38.104305,175.025940,z12
Tagged Aerial URL: https://basemaps.linz.govt.nz/?i=aerial@pr-465
=> feat(aerial): Config imagery ōtorohanga_urban_2021_0.1m_RGB into Aerial Map. BM-489

config/tileset/aerial.json
Imagery imported for antipodes-islands_satellite_2019-2020_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FZY5MYGMYCH5WPDCP1DMYHZ8&p=NZTM2000Quad&debug#@-49.668296,178.775313,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FZY5N4E6Q4P2TV3MP94BKTMB&p=WebMercatorQuad&debug#@-49.678293,178.769531,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-476#@-49.668296,178.775313,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-476#@-49.678293,178.769531,z12
=> feat(aerial): Config imagery antipodes-islands_satellite_2019-2020_0.5m_RGB into Aerial Map. BM-507

config/tileset/aerial.json
Imagery imported for auckland-islands_satellite_2014-2021_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FZYE8BB9EBP892F3JQSSSHQG&p=NZTM2000Quad&debug#@-50.685864,166.100465,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FZYE8NX9DE6ZA3Y5VK1QAHNK&p=WebMercatorQuad&debug#@-50.708634,166.069336,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-482#@-50.685864,166.100465,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-482#@-50.708634,166.069336,z12
=> feat(aerial): Config imagery auckland-islands_satellite_2014-2021_0.5m_RGB into Aerial Map. BM-508

config/tileset/aerial.json
Imagery imported for bounty-islands_satellite_2020_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FZYK75PS5DM0BKGZ885RZ94D&p=NZTM2000Quad&debug#@-47.761324,179.033890,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FZYK7C7Y9GHSPRKM4B4C5RSY&p=WebMercatorQuad&debug#@-47.761484,179.033203,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-483#@-47.761324,179.033890,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-483#@-47.761484,179.033203,z12
=> feat(aerial): Config imagery bounty-islands_satellite_2020_0.5m_RGB into Aerial Map. BM-509

config/tileset/aerial.json
Imagery imported for campbell-island-motu-ihupuku_satellite_2015-2020_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G00E8Y3HSN66NDDKP89H2VTT&p=NZTM2000Quad&debug#@-52.544712,169.196903,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G00E9728953QMD6NY7BVDGSN&p=WebMercatorQuad&debug#@-52.549636,169.101562,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-485#@-52.544712,169.196903,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-485#@-52.549636,169.101562,z12
=> feat(aerial): Config imagery campbell-island-motu-ihupuku_satellite_2015-2020_0.5m_RGB into Aerial Map. BM-510

config/tileset/aerial.json
Imagery imported for kermadec-islands_satellite_2020-2021_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G00S1WQ72T0PCN9T7QNE81V0&p=NZTM2000Quad&debug#@-30.285724,-178.334960,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G00S25RMGY8FEHWFRYNPFDFJ&p=WebMercatorQuad&debug#@-30.306503,-178.341064,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-486#@-30.285724,-178.334960,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-486#@-30.306503,-178.341064,z12
=> feat(aerial): Config imagery kermadec-islands_satellite_2020-2021_0.5m_RGB into Aerial Map. BM-511

config/tileset/aerial.json
Imagery imported for nz-nearshore-islands_satellite_2010-2021_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G00XY0TVJJ4QVJ7988TCKGWS&p=NZTM2000Quad&debug#@-40.517192,172.071141,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G00XYQ8YKAZC7P5QJ4BPCX22&p=WebMercatorQuad&debug#@-40.780541,171.710815,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-487#@-40.517192,172.071141,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-487#@-40.780541,171.710815,z12
=> feat(aerial): Config imagery nz-nearshore-islands_satellite_2010-2021_0.5m_RGB into Aerial Map. BM-513

config/tileset/aerial.json
Imagery imported for snares-islands-tini-heke_satellite_2019-2020_0.5m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G011MVHNRWAMSQSPBKXVAEC3&p=NZTM2000Quad&debug#@-48.042018,166.560930,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G011N3MVQVYP0Q1025R45219&p=WebMercatorQuad&debug#@-48.034019,166.552734,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-488#@-48.042018,166.560930,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-488#@-48.034019,166.552734,z12
=> feat(aerial): Config imagery snares-islands-tini-heke_satellite_2019-2020_0.5m_RGB into Aerial Map. BM-512

config/style/topolite.json
Many layers in this style have maxzoom set to 24. This causes a problem because when zooming past 24, instead of just magnifying, the layers get hidden. With the maxzoom removed, the client can zoom in as far as desired and the layers will remain visible, which I think is the intent of the style.
=> fix(vector): remove maxzoom: 24 from topolite style

src/commands/imagery.ts, src/config/tileset.updater.ts
Example
```bash
./bin/bmc.js imagery  \
s3://linz-basemaps/2193/ashburton-urban_2022_7.5cm/01G20Y1MS9826TJ53XND1DNZP6  \
--name ashburton-urban_2022_7.5cm  \
--tile-matrix-set NZTM2000Quad
```
This is a temporary script until the COG creation process imports the configuration for us.
=> feat(scripts): add script to import imagery configuration from folder of tiffs

config/tileset/aerial.json
Imagery imported for waipa_urban_2021_0.1m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G28WB9GKP01A8DPYWG9CBMN1&p=NZTM2000Quad&debug#@-37.984133,175.383542,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G28WC5349Y0J3CGWGTZ796DD&p=WebMercatorQuad&debug#@-37.978845,175.385742,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-517#@-37.984133,175.383542,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-517#@-37.978845,175.385742,z12
=> feat(aerial): Config imagery waipa_urban_2021_0.1m_RGB into Aerial Map. BM-557

config/tileset/aerial.json
NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G4XPNP9JTGGPABCFRWC4N21E&p=NZTM2000Quad&debug=true#@-36.6929361,175.5201417,z6.0564
WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G4XPQKF6VB9SXCQ93R2XC1W8&debug=true#@-36.8511386,175.1625004,z8.2268
=> feat(aerial): Reprocess the Auckland rurual 2020 imagery to add new tiles.

config/tileset/aerial.json
Imagery imported for auckland_rural_2022_0.075m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G6HJ9S4PGK6MTVEZWWHV56QN&p=NZTM2000Quad&debug#@-36.708278,174.559732,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G6HJBFJRBKJ7FQPHVRACKMNQ&p=WebMercatorQuad&debug#@-36.703660,174.567261,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-566#@-36.708278,174.559732,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-566#@-36.703660,174.567261,z12
=> feat(aerial): Config imagery auckland_rural_2022_0.075m_RGB into Aerial Map. BM-593

config/tileset/aerial.json
Imagery imported for tasman_rural_2022_0.3m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G75YD43EBA980HFWVF6ZFV6B&p=NZTM2000Quad&debug#@-40.983623,172.907840,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G75YDG4KFEZ5BAGTPHMEAPP7&p=WebMercatorQuad&debug#@-41.013066,172.880859,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-576#@-40.983623,172.907840,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-576#@-41.013066,172.880859,z12
=> feat(aerial): Config imagery tasman_rural_2022_0.3m_RGB into Aerial Map. BM-620

config/tileset/aerial.json
Imagery imported for nz_satellite_2021-2022_10m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G73E4AMSQ91TXQ3KC90NNPA0&p=NZTM2000Quad&debug#@-41.108460,174.305964,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G73E5DZKE9NSW6E41QQRT28T&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-572#@-41.108460,174.305964,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-572#@-41.376809,172.968750,z12
=> feat(aerial): Config imagery nz_satellite_2021-2022_10m_RGB into Aerial Map. BM-615

config/tileset/aerial.json
Imagery imported for nelson_urban_2022_0.075m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G87CWVWSG7KWE3DHC6R18BCX&p=NZTM2000Quad&debug#@-41.258470,173.374624,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G87CXGF81D5CVT22B038BCM1&p=WebMercatorQuad&debug#@-41.253032,173.380737,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-587#@-41.258470,173.374624,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-587#@-41.253032,173.380737,z12
=> feat(aerial): Config imagery nelson_urban_2022_0.075m_RGB into Aerial Map. BM-630

config/tileset/aerial.json
Sets 24 imagery surveys to minZoom 32 - these all need to be moved into a `historical` config as they have been superceded by more recent aerial imagery surveys. This is the first step toward creation of that config and cleaning up the `aerial` config.
=> feat(aerial): don't show historical imagery surveys

config/tileset/aerial.json
Imagery imported for marlborough_rural_2021-2022_0.25m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GAMZ84DPHCND4PG6BD0W999A&p=NZTM2000Quad&debug#@-41.929973,173.496536,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GAMZ9988GKX5JF0F0EW2R9Q3&p=WebMercatorQuad&debug#@-41.926803,173.496094,z12
=> feat(aerial): Config imagery marlborough_rural_2021-2022_0.25m_RGB into Aerial Map. BM-658

config/tileset/aerial.json
Imagery imported for hamilton_urban_2020-2021_0.05m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GASE5J7NJSZRVD92X9J655TQ&p=NZTM2000Quad&debug#@-37.777067,175.265795,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GASE6HES5VTVKV66G5S82KV3&p=WebMercatorQuad&debug#@-37.770715,175.264893,z12
Tagged Aerial Map NZTM2000Quad: https://dev.basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-2RLMcERykfYiawLek9bQ8NdHeSzU8VwjjweANR2mwa5P.json.gz&tileMatrix=NZTM2000Quad#@-37.7669740,175.2726161,z10.7316
=> feat(aerial): Config imagery hamilton_urban_2020-2021_0.05m_RGB into Aerial Map. BM-660

config/tileset/aerial.json
Imagery imported for hawkes-bay_rural_2021-2022_0.3m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GBPH2Y0Q4PENH4T22PGJB521&p=NZTM2000Quad&debug#@-39.524229,177.064088,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GBPH42RKHGCSHRB3EMZVZD91&p=WebMercatorQuad&debug#@-39.504041,177.011719,z12
Tagged Aerial Map NZTM2000Quad: https://dev.basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-DKPfK9CoyHL6bH3nRuctPbBHmsyRfe2X5aGQedNckNHD.json.gz#@-39.524229,177.064088,z9
Tagged Aerial Map WebMercatorQuad: https://dev.basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-DKPfK9CoyHL6bH3nRuctPbBHmsyRfe2X5aGQedNckNHD.json.gz#@-39.504041,17 …
=> feat(aerial): Config imagery hawkes-bay_rural_2021-2022_0.3m_RGB into Aerial Map. BM-663

config/tileset/aerial.json
Imagery imported for wellington-city_urban_2021_0.075m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GBRRFSNR0V1N50WP0H1E7SDP&p=NZTM2000Quad&debug#@-41.256395,174.776038,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GBRRG6Z6Q8SJNECE7K49M88R&p=WebMercatorQuad&debug#@-41.261291,174.776001,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-3RPVdxmo9kjoBHB8VBzr8YDjFRZSHQvNh2j7x2Mt6gL2.json.gz#@-41.256395,174.776038,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-3RPVdxmo9kjoBHB8VBzr8YDjFRZSHQvNh2j7x2Mt6gL2.json.gz#@-41.261291,174.7760 …
=> feat(aerial): Config imagery wellington-city_urban_2021_0.075m_RGB into Aerial Map. BM-668

config/tileset/aerial.json
Imagery imported for hawkes-bay_urban_2022_0.1m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GD1TW8AFTNCGHNG97P9MDFYZ&p=NZTM2000Quad&debug#@-39.866450,176.669721,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GD1TXCTKWJ2TKJR8ZVKNA546&p=WebMercatorQuad&debug#@-39.857046,176.682129,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-AuXga7zCok1JAkEvrJbfa8SHhwpnqPANLnrbTs4Y8A9N.json.gz#@-39.866450,176.669721,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-AuXga7zCok1JAkEvrJbfa8SHhwpnqPANLnrbTs4Y8A9N.json.gz#@-39.857046,176.682129,z12
=> feat(aerial): Config imagery hawkes-bay_urban_2022_0.1m_RGB into Aerial Map. BM-676

config/tileset/aerial.json
Imagery imported for hawkes-bay_urban_2022_0.05m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GD1VBBC9BX6YD2BZYN0S00YK&p=NZTM2000Quad&debug#@-39.481069,176.876791,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GD1VBRXY4647H7ATEXNSNZ94&p=WebMercatorQuad&debug#@-39.479666,176.871643,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-aWmVEQHXpjBPh3XsyZpKdYjpR8UZR27AzsazCx3zqRN.json.gz#@-39.481069,176.876791,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-aWmVEQHXpjBPh3XsyZpKdYjpR8UZR27AzsazCx3zqRN.json.gz#@-39.479666,176.871643,z12
=> feat(aerial): Config imagery hawkes-bay_urban_2022_0.05m_RGB into Aerial Map. BM-675

config/tileset/aerial.json
Imagery imported for tauranga-city_urban_2022_0.1m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GD1V79CP27V3FD5XFWGCTPEM&p=NZTM2000Quad&debug#@-37.710551,176.227821,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GD1V81RYJDH8NWK7C33PVNWR&p=WebMercatorQuad&debug#@-37.709899,176.237183,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-E4qmFMibMKxpuCmUByUbkpac5beTGicBwvDPRE8HLFUM.json.gz#@-37.710551,176.227821,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-E4qmFMibMKxpuCmUByUbkpac5beTGicBwvDPRE8HLFUM.json.gz#@-37.709899,176.237183,z …
=> feat(aerial): Config imagery tauranga-city_urban_2022_0.1m_RGB into Aerial Map. BM-677

config/tileset/aerial.json
Imagery imported for taranaki_rural_2021-2022_0.25m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GDKFTY5BPAHMSKKVC336J9Y2&p=NZTM2000Quad&debug#@-39.262026,174.384423,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GDKFVY7VZ7CVYGYG02FXSEMJ&p=WebMercatorQuad&debug#@-39.300299,174.396973,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-2v6sDmUwaCkkL6NPavr6oznkaUKvNB1vfDVKAjB9yS4i.json.gz#@-39.262026,174.384423,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-2v6sDmUwaCkkL6NPavr6oznkaUKvNB1vfDVKAjB9yS4i.json.gz#@-39.300299,174.396973, …
=> feat(aerial): Config imagery taranaki_rural_2021-2022_0.25m_RGB into Aerial Map. BM-682

config/tileset/aerial.json
Imagery imported for taranaki_urban_2022_0.1m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GDM79KSKKCZ4FQCX5S2Q4BDQ&p=NZTM2000Quad&debug#@-39.225137,174.234935,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GDM7ACWGP9QZP7V3MF4MPKH8&p=WebMercatorQuad&debug#@-39.227998,174.226685,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-5wEKoMbMdvnAzSua1LYM72N6e1veu8kwoFgGZJzD1Br1.json.gz#@-39.225137,174.234935,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-5wEKoMbMdvnAzSua1LYM72N6e1veu8kwoFgGZJzD1Br1.json.gz#@-39.227998,174.226685,z12
=> feat(aerial): Config imagery taranaki_urban_2022_0.1m_RGB into Aerial Map. BM-684

config/tileset/aerial.json
Imagery imported for taranaki_urban_2022_0.05m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01GDM781KPM27STN22MDPWC57Y&p=NZTM2000Quad&debug#@-39.747709,174.536838,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01GDM7896HY2KQG4K3ESSZMPH6&p=WebMercatorQuad&debug#@-39.747322,174.539795,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&config=s3://linz-basemaps/config/config-4T2tSBxKVrrFWRMterRfv4AxbRWvncvWJW7dLdpgZyss.json.gz#@-39.747709,174.536838,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&config=s3://linz-basemaps/config/config-4T2tSBxKVrrFWRMterRfv4AxbRWvncvWJW7dLdpgZyss.json.gz#@-39.747322,174.539795,z12
=> feat(aerial): Config imagery taranaki_urban_2022_0.05m_RGB into Aerial Map. BM-683

config/tileset/aerial.json
- Layer update [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01GGDTRTDV2BA47P4TQ6CGWMFR&p=NZTM2000Quad&debug#@-41.137640,173.242786,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-hddppB3zWxHW4uXd5u8FNYe5TkgeWPZ3ftAVbmZHtcv.json.gz&p=NZTM2000Quad&debug#@-41.137640,173.242786,z9)
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01GGDTSGRK0Z4C70WXBYMEXK4X&p=WebMercatorQuad&debug#@-41.145570,173.221436,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-hddppB3zWxHW4uXd5u8FNYe5TkgeWPZ3ftAVbmZHtcv.json.gz&p=WebMercatorQuad&debug#@-41.145570,173.221436,z12)
=> config(aerial): Update the top of the south flood 2022 imagery.

config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01GG8G03K4N284BJ7Q0DFTRW6P&p=NZTM2000Quad&debug#@-46.451003,168.376325,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-xu4uP4JMqJDVeR2bEUAWWkHFy6vyFADHqC1DRgu8anN.json.gz&p=NZTM2000Quad&debug#@-46.451003,168.376325,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01GG8G0NQDH4F6XPCMQS312DRK&p=WebMercatorQuad&debug#@-46.460566,168.365479,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-xu4uP4JMqJDVeR2bEUAWWkHFy6vyFADHqC1DRgu8anN.json.gz&p=WebMercatorQuad&debug#@-46.460566,168.365479,z12)
- Zoom level updated. min zoom 14 -> 32
- Zoom level updated. min zoom 14 -> 32
=> config(aerial): Config Invercargill rural imagery into aerial map. BM-698

config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01GHW1Y474AHB191P8SRKENK7Y&p=NZTM2000Quad&debug#@-38.173173,177.266888,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-A1AndnQSPSPRFMFgdqonVq4UM6RCqTnZgdauo3Q8mRqv.json.gz&p=NZTM2000Quad&debug#@-38.173173,177.266888,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01GHW1ZWNS4N0GP9TAM09WHPBC&p=WebMercatorQuad&debug#@-38.199339,177.297363,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-A1AndnQSPSPRFMFgdqonVq4UM6RCqTnZgdauo3Q8mRqv.json.gz&p=WebMercatorQuad&debug#@-38.199339,177.297363,z12)
- Zoom level updated. min zoom 13 -> 32
=> feat(aerial): Config Bay of Plenty Rural 2021-2022 into Aerial Map.

config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CEcZPQAQE1qQ6jgyj9fn8VZDSHqni9KkaxfqhhhfywN.json.gz&i=waimate-2021-0.075m&p=NZTM2000Quad&debug#@-44.718672,170.832915,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CEcZPQAQE1qQ6jgyj9fn8VZDSHqni9KkaxfqhhhfywN.json.gz&p=NZTM2000Quad&debug#@-44.718672,170.832915,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CEcZPQAQE1qQ6jgyj9fn8VZDSHqni9KkaxfqhhhfywN.json.gz&i=waimate-2021-0.075m&p=WebMercatorQuad&debug#@-44.725272,170.837402,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CEcZPQAQE1qQ6jgyj9fn8VZDSHqni9KkaxfqhhhfywN.json.gz&p=WebMercatorQuad&debug# …
=> feat(aerial): Config imagery waimate_2021_0.075m into Aerial Map. 

config/tileset/aerial.json
- [NZTM2000Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-HSjr4Ltgrd2cqgHcT1vAFJsXbMVKKimWT1ksEc5EJZsp.json.gz&i=palmerston-north-2022-0.125m&p=NZTM2000Quad&debug#@-40.352739,175.653911,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-HSjr4Ltgrd2cqgHcT1vAFJsXbMVKKimWT1ksEc5EJZsp.json.gz&p=NZTM2000Quad&debug#@-40.352739,175.653911,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-HSjr4Ltgrd2cqgHcT1vAFJsXbMVKKimWT1ksEc5EJZsp.json.gz&i=palmerston-north-2022-0.125m&p=WebMercatorQuad&debug#@-40.354917,175.654907,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-HSjr4Ltgrd2cqgHcT1vAFJsXbMVKKimWT1ksEc5EJZsp.json.gz&p …
=> feat(aerial): Config imagery palmerston_north_2022_0.125m into Aerial Map. 

config/tileset/aerial.json
- [NZTM2000Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-Ared7eYB2Psc2MmcFNYTJcBb3AiTTQvmX6TaJ2XAYFiG.json.gz&i=ashburton-urban-2021-2022-0.075m&p=NZTM2000Quad&debug#@-43.851402,171.617772,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-Ared7eYB2Psc2MmcFNYTJcBb3AiTTQvmX6TaJ2XAYFiG.json.gz&p=NZTM2000Quad&debug#@-43.851402,171.617772,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-Ared7eYB2Psc2MmcFNYTJcBb3AiTTQvmX6TaJ2XAYFiG.json.gz&i=ashburton-urban-2021-2022-0.075m&p=WebMercatorQuad&debug#@-43.851365,171.622925,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-Ared7eYB2Psc2MmcFNYTJcBb3AiTTQvmX6TaJ2XAYFiG.j …
=> feat(aerial): Config imagery ashburton_urban_2021-2022_0.075m into Aerial Map. 

config/tileset/aerial.json
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CaNAGKZVGB2PAT5WLh9rDoQ2cqLKdaPw2SLjZ5vyYH3a.json.gz&i=tasman-rural-2020-0.3m&p=WebMercatorQuad&debug#@-41.836828,172.529297,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CaNAGKZVGB2PAT5WLh9rDoQ2cqLKdaPw2SLjZ5vyYH3a.json.gz&p=WebMercatorQuad&debug#@-41.836828,172.529297,z12)
=> fix(aerial): correct imagery id for tasman 2020 rural BM-751

config/tileset/aerial.json
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-2b6cBzCW1ffduBdyuhRW62CUDXspnf8ikQZY5omXydCG.json.gz&i=nz-satellite-2020-2021-10m&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-2b6cBzCW1ffduBdyuhRW62CUDXspnf8ikQZY5omXydCG.json.gz&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12)
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-2b6cBzCW1ffduBdyuhRW62CUDXspnf8ikQZY5omXydCG.json.gz&i=nz-satellite-2021-2022-10m&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-2b6cBzCW1ffduBdyuhRW6 …
=> fix(aerial): Switch the satellite to new data to fix the broken overview.

config/style/aerialhybrid.json
* [aerialhybrid](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-127GvctxD4sYB2y3KvsheyfK6mVVg4UaqNgmwAKtEFdy.json.gz&i=topographic&s=aerialhybrid&debug)
=> config(style): Update the aerial hybrid style to remove topo250 refference

config/tileset/aerial.json
- Zoom level updated. min zoom undefined -> 32
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-7AAbmAyS5vsPcgZG9E2ja8RtyTALp7QeoewtGE6d6yyS.json.gz&i=nz-satellite-2020-2021-10m&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-7AAbmAyS5vsPcgZG9E2ja8RtyTALp7QeoewtGE6d6yyS.json.gz&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12)
- Layer update [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-7AAbmAyS5vsPcgZG9E2ja8RtyTALp7QeoewtGE6d6yyS.json.gz&i=nz-satellite-2021-2022-10m&p=WebMercatorQuad&debug#@-41.376809,172.968750,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basem …
=> fix(aerial): Revert the satellite layer after overview been fixed and generated.

config/tileset/aerial.json
Deprioritising a number of Bay of Plenty datasets as recent 20cm Rural + 10cm Tauranga imagery provide full coverage. Bay of Plenty councils confused by older 10cm urbans in Whakatāne, I think it makes sense to remove them too.
=> feat(aerial): don't show Bay of Plenty urbans

config/tileset/aerial.json
This is a temporary measure for the Cyclone Gabrielle response until we expose the full date in some other way in the Basemaps UI.
Also grouped this imagery with other Event imagery.
=> feat(aerial): add date to cyclone imagery title

config/tileset/aerial.json
*By moving the disabled layer into independent configs, we can remove and clean up the aerial config file. Also, after standardised imagery name, we can now access individual imagery by copy the name from config into api.*
*Our aerial.json config file gets hard to manage to have a mixture of different configs, and also get this ready for historical configs.*
=> feat(config): Refactoring config to separate all individual imagery and standardise imagery names

config/tileset/scanned.post19891231.json, config/tileset/scanned.pre19900101.json
Changes the scanned composite tileset identifiers
Alignment with other tilesets that use `-` instead of `snake_case` in their tileset names and identifiers.
=> chore: update scanned composite ids BM-892

config/tileset/aerial.json, config/tileset/event.cyclonegabrielle.json
feat(aerial): update Gisborne Cyclone Gabrielle imagery in Aerial and Event Cyclone Gabrielle config
=> config(raster): update gisborne-cyclone-gabrielle_2023_0.2m

config/style/topographic.json
When Maplibre cannot find fonts it fails to render the tile, the topographic styles referenced fonts that are not in ../fonts and when rendering these features it fails to render the map.
Swap instances of missing fonts with fonts that exist.
*If not applicable, provide explanation of why.*
=> fix(vector): replace missing fonts

.prettierrc.cjs, config/style/aerialhybrid.json, config/style/basic.json, config/style/positron.json, config/style/topographic.json, config/style/topolite.json, package-lock.json, package.json
Style config might have different order in layers when export from maputinik, this makes use hard to review the changes.
We using prettier json sort plughin to sort all the keys in the style config json files.
=> ci: Sort style config files by prettier json sort plugin.

config/style/topographic.json
- separate style for place, natural and water names
- update the topographic and aerialhybrid styles
Re-import the latest style json manually from maputnik server. They format getting changed a little bit as previously we imported by the cli script.
=> config(style): Split place names into place, natural and water classes. BM-761

scripts/bmc.sh
Basemaps' master branch can be a little broken, use a locked version to prevent using a broken build
locks the basemaps cli to the last known good version until a new release is made.
=> fix: lock basemaps cli to last known good version

config/tileset/aerial.json
In attempting to place the new Waikato Rural aerial imagery appropriately between Auckland Rural imagery, Waikato Urbans were accidentally ordered below the new rural imagery. This PR attempts to fix this and place Waikato Urbans back on top.
=> fix: move Waikato urbans above new Waikato rural

.github/workflows/build.yml, scripts/bmc.sh
Upgrade the cli version for the ci cd.
The new config cli will be able to bundle the elevation config and individual vector tilesets. And it also add the cache to the `linz-basemaps-scrach` bucket for bundling performance.
=> build: Upgrade the basemaps cli to version v7.2.0

.github/workflows/build.yml
Asset not been uploaded into production, we got a changed asset recently, because the ordering for the files are based on the `URL.href` instead of string path now. 
un-comment of the code that copy asset into production.
=> fix(ci): Fix Upload asset file into production bucket.

config/tileset/gisborne/imagery/gisborne-cyclone-bola-sn11485-1988-0.4m.json
Change category of gisborne-cyclone-bola-sn11485-1988-0.4m to Event rather than Scanned Aerial Photos
=> fix: gisborne-cyclone-bola-sn11485-1988-0.4m change category to event

config/tileset/elevation.json
the 1m dems are not full coverage of NZ, so add the 8m DEM as a baselayer for all other DEMS
Adds Geographx 8m DEM
=> feat(elevation): add nz 8m dem as base for all elevation

config/tileset/elevation.json
The 2013 LiDAR is the lowest resolution for the wellington region, so it should be the lowest priority.
Moves wellington region to the lowest priority for wellington.
=> fix(elevation): correct wellingtion lidar ordering

.github/workflows/build.yml
Currently the tileset config background has to be defined as hex string. We are migrating them into rgb in the future. Just update the cli version to allow the bundling parser to allow both hex and rgd. https://github.com/linz/basemaps/commit/23df7debe6638946631d10d53bc809c53afa92f6
update cli version
=> ci: Upgrade the cli version to allow rgb background in the tileset config.

.github/workflows/build.yml
the cli was linked to a specific version to fix a couple of bugs these bugs have now been reelased.
swap from a exact version of basemaps cli to the latest released version v7.x.x
=> build: use latest v7.x.x basemaps cli version

config/tileset/elevation.json
Waikato had updated tiles added to the Registry of Open Data on AWS, Basemaps Web Mercator layer needs to be updated to match.
Updated the tileset ID.
Basemaps previews of that tileset ID: https://basemaps.linz.govt.nz/@-37.8921956,175.6933593,z9?style=01J546JDQCQ0H9735NHN4P903W&tileMatrix=WebMercatorQuad&debug&config=4CaC4znMfJBq41Lr3HetGWsVkRE8SDHmHXcfSxTG8yVxqAiFUPFxSNpB2HJZWcSnFdpxDoszHzqcSYhZiyJkoA5paKFDNQKnZCoiZhs8w9VvENBWRzyguhxkJeNU3ygJ7c6GpyNKe9jQZgy7HNXyTXJUR7vifw7W82HE9ZcfuDgHpAvANuyhX2Xhr8Koft3LypzKsVbpJdeq
=> feat(elevation): update Waikato 1m DEM (2021) with added tiles

config/style/label.json, config/style/labels.json
It would be nice to layer all the vector data ontop of all the individual aerial imagery datasets that we have.
Add a "labels" style which has no base layer and overlays labels and roads.
When it is deployed we can verify it looks good across all the individual layers.
=> config: add a label base style BM-1066

config/style/aerialhybrid.json, config/style/labels.json
In both the `aerialhybrid.json` and `labels.json` stylesheets, the `landfill` layer references an unsupported font.
For both stylesheets, I have updated the `landfill` layer's `text-font` key-value pair:
| Before | After |
| - | - |
| `Roboto Condensed Italic` | `Roboto Light Italic` |
> Note: The `landfill` layer is also only one referencing the `Roboto Condensed Italic` font.
Before, tiles containing a `landfill` layer element would not render because of the unsupported font.
| Before |
| - |
| ![image](https://github.com/user-attachments/assets/f2e820c8-a1fb-4d95-b057-54f1c10f013a) |
Now, such tiles render without issue.
| After |
| - |
| ![image](https://github.com/user-attachments/assets/f834bc48-46fa-4809-ade1-9694a797d24b)|
Path used for testing: …
=> fix(vector): replace missing fonts BM-1091

config/tileset/elevation.json
The elevation config was originally ordered by region then date, however many regions overlap and it is difficult to work out what the order should be between regions.
Reordered the config by island (North/South) then date.
Will check National 1m DEM after this is merged.
=> feat(elevation): reorder based on island then date

.github/workflows/build.yml
As a Basemaps developer, having to look up the path to the most recent **`assets.tar.co`** file stored in **AWS S3** is inconvenient. It would save me time and effort if a copy of the latest assets file were stored in a fixed location with a fixed name, similar to the bundled config file (`config-latest.json.gz`).
When I run **Basemaps** locally, it's not always the case that I can run the **`basemaps/server`** package using the **`config-latest.json.gz`** file. For example, if I make changes to the vector tile stylesheets and want to test them locally, I need to bundle the config file myself. To do so, I have to specify the `--assets` parameter to enable fonts, glyphs, and sprites. Otherwise, they will not load on the map.
Currently, assets files are uploaded to **AWS S3** with a hash …
=> ci: store a 'latest' assets file in AWS S3 BM-1094

config/tileset/elevation.json
Adds the 2193 version of the New Zealand Contour-Interpolated 8m DEM which was missing when this configuration was originally created.
Add 8m DEM link to elevation.json
Before:
After:
=> feat: Add 2193 version of New Zealand Contour-Interpolated 8m DEM

config/style/topographic.json
This change aims to improve the visibility, vibrancy and detail in the dynamic hill shade derived from the LINZ 1m DEM layer. 
The hill shade has been changed in the following ways:
- increased visibility at zoom level 0-7
- increased visibility at zoom level 14 and above
- locked sun angle at 315 degrees from north
- slightly increased opacity
- generally decreased highlights across all zoom levels
- minor change to hill shade shadow, highlight and accent colour
Examples for the change:
Before:
After:
Before:
After:
Before:
After:
=> feat(style): Improve topographic vector map hillshades. BM-1140

config/tileset/elevation.json
These three datasets are being reintroduced as they fill minor gaps that were not reflown as part of later surveys.
Reintroduced 3 datasets into elevation.json
Abel Tasman and Golden Bay 2016:
Christchurch and Ashley River 2018-2019:
Christchurch and Selwyn 2015:
=> feat(elevation): reintroduce older datasets not fully replaced

.github/workflows/build.yml
`getsentry/action-visual-snapshot` has been deprecated and archived, it is no longer supported, github has recently removed support for the artifacts API it was using to store the images, causing all of these actions to fail.
Fork the github action and update it to support the newer github actions artifacts API.
this is a temporary fix with the intention to replace this github action with another more supported action in the near term.
Checking to see if the build succeeds after this is merged.
=> build: upgrade visual snapshot to support new artifacts api

config/tileset/elevation.dsm.json
We now have DSM elevation data available to process and serve through Basemaps as `Terrain-RGB` tiles. This work defines a tileset to collage the DSM datasets. As part of this work, we have run each dataset through the [basemaps-imagery-import-cogify] Argo workflow to re-project it into `3857`.
We have cloned the existing [elevation] tileset config as a new file titled `elevation.dsm.json` and made the following modifications:
1. **Metadata**
```json
{
"id": "ts_elevation",
"name": "elevation",
"type": "raster",
"description": "Elevation Basemap",
"title": "Elevation",
"category": "Elevation",
...
```
```json
{
"id": "ts_elevation-dsm",
"name": "elevation-dsm",
"type": "raster",
"description": "Elevation DSM Basemap",
"title": "Elevation DSM",
"category": "Elevation",
...
```
2. …
=> config(elevation): prepare elevation-dsm tileset BM-1246

config/tileset/elevation.json
This config is split into North Island and South Island, which hasn't been reflected with recent automated pull requests. Moving things to the right spot to avoid confusion.
=> chore: rearrange elevation dataset survey ordering

.github/CODEOWNERS
@JBLINZ needs to be able to sign-off on tileset changes
Updated CODEOWNERS file to specify Basemaps team as owner of tilesets rather than Basemaps developers.
GitHub validates the CODEOWNERS file as valid.
=> chore: set Basemaps team as CODEOWNER of tilesets

config/style/labels-v2.json, config/style/topolite-v2.json
We only updated the source urls for topographic-v2 but not for topolite-v2 and labels-v2.
Update topolite-v2 and labels-v2 to support NZTM shortbread tiles.
=> fix(style): Fix the topolite-v2 and labels-v2 to styles to support NZTM2000Quad TileMatrix.

config/tileset/auckland/imagery/auckland-2010-2012-0.5m.json, config/tileset/auckland/imagery/auckland-2017-0.075m.json
Fixing cases of using underscores instead of dashes, as well a trailing 0 in the GSD.
=> fix: correct auckland dataset id formatting

config/tileset/hillshade.dsm.json, config/tileset/hillshade.igor.dsm.json
Two new national DSM hillshade layers have been published in AWS ODR. We want these layers to be published via basemaps for individual use and combined use in our various configs (Aerial, Topographic v2, NZ Topo). 
Layers will be published and regularly updated in ODR in 2193. From there, we must consume the data and create a 3857 version.
dsm: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-9ntcn?tab=summary&uid=2869aaa1-aad7-45e8-863d-0a40879fec93
dsm igor: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-z55f9?tab=summary&uid=cbb70f60-5848-4220-8733-862483c27d0c
dsm overview?: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-gh8fb?tab=summary&uid=7cf64b4e-3236-4f14-a295-cfbf9eab0436
dsm igor overview?: …
=> feat: add dsm hillshade layers BM-1277

config/tileset/auckland/imagery/auckland-2010-2012-0.5m.json, config/tileset/auckland/imagery/auckland-2017-0.075m.json, config/tileset/auckland/imagery/auckland-2020-0.075m.json, config/tileset/auckland/imagery/auckland-2022-0.075m.json, config/tileset/bay-of-plenty/imagery/bay-of-plenty-2020-0.1m.json, config/tileset/bay-of-plenty/imagery/bay-of-plenty-2021-0.2m.json, config/tileset/hawkes-bay/imagery/hawkes-bay-2022-0.05m.json, config/tileset/hawkes-bay/imagery/hawkes-bay-2022-0.1m.json, config/tileset/otago/imagery/otago-2019-2021-0.3m.json, config/tileset/tasman/imagery/tasman-2022-0.3m.json, config/tileset/tasman/imagery/tasman-rural-2018-2019-0.3m.json, config/tileset/wellington/imagery/carterton-2021-0.075m.json, config/tileset/wellington/imagery/masterton-2021-0.075m.json
Aerial Imagery PRs with the 'Aerial Imagery Deletes' messages are breaking existing WMTS links
=> fix: add back urban and rural for broken wmts links BM-1334

config/style/labels-v2.json, config/style/topolite-v2.json
We've recently upgraded our labels dataset and refined the zoom level ranges for various feature groups.
From this, we refined our `topographic-v2` style:
- https://github.com/linz/basemaps-config/pull/1218
- https://github.com/linz/basemaps-config/pull/1252
Now, we want to apply similar refinements to our `labels-v2` and `topolite-v2` styles.
- **`labels-v2`**
- Replaced the `place_labels` style entries with Karl's new ones targeting the new data.
- Updated the `minzoom` value to `13` for the following style entries:
- `All-FootTrack-Labels`
- `Transport-FootTracks`
- `Transport-FootTracks-Shadow`
- Updated the `maxzoom` value to `15` for the following style entries:
- `Place-Label-Suburb`
- **`topolite-v2`**
- Replaced the `place_labels` style entries with Karl's new ones targeting the …
=> config(vector): update the labels-v2 and topolite-v2 styles BM-1349
