- config/tileset/aerial.json
NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FC200TCKR7ZTJEN6Q8ZJAET1&p=NZTM2000Quad&debug=true#@-39.4457357,176.8846301,z5.9119
WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FC1ZY5V4XCEXDSWT3FE3A8VM&debug=true#@-39.4936791,177.1762710,z7.8681 
New Images
Old Images
> feat(aerial): Import hawkes-bay_rural_2019-2020_0.3m_RGB config into basemaps.

- config/tileset/aerial.json
NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01FC534VYVGP4WMS19M8SV1E6S&p=NZTM2000Quad&debug=true#@-41.0561075,175.6696346,z8.7879
WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01FC53660FJRP02Z4GZAQPZJV6&debug=true#@-41.0666238,175.6453821,z10.2593
> feat(aerial): Import carterton_urban_2021_0-075m_RGB into basemap.

- config/tileset/aerial.json
> fix(aerial): wellington urban 2021 is below porirua urban.

- config/tileset/topographic.json
- move waterfall points from water layer into waterway layer.
- fix the tag for landcover relief layers.
- Move some tracks into transportation layer from centerline layer.
> feat(vector): Fix some incorrect outlying islands layers.

- config/style/topolike.json
https://dev.basemaps.linz.govt.nz/?i=topographic#@-41.8899962,174.0492437,z5
> feat(vector): Update the latest style json.

- config/style/topolike.json
Ready to QA in https://dev.basemaps.linz.govt.nz/?i=topographic#@-41.2300840,175.9418472,z5.0468
> feat(vector): Update to the latest style json

- config/tileset/topographic.json
https://dev.basemaps.linz.govt.nz/?i=topographic#@-21.4590289,161.0109410,z1.6316
> feat(vector): Import ocean layer into vector map

- config/tileset/topographic.json
https://dev.basemaps.linz.govt.nz/?i=topographic#@-43.7330709,-176.2847611,z12.3138
> feat(vector): Fix missing chatham layers.

- config/style/topolike.json
https://dev.basemaps.linz.govt.nz/?i=topographic#@-41.8899962,174.0492437,z5
> feat(vector): Update the latest stylejson

- config/tileset/topographic.json
https://dev.basemaps.linz.govt.nz/?s=topolike&i=topographic#@-44.1821262,-179.5164402,z5.1344
> feat(vector): Import latest vector data to include fix and building poi features

- config/tileset/topographic.json
Already update the config into dev for QA
https://dev.basemaps.linz.govt.nz/?s=topographic&i=topographic#@-41.3123683,174.7518760,z12.6359
> config(vector): Remove ocean layer and update building poi to zoom 12

- config/tileset/topographic.json
https://dev.basemaps.linz.govt.nz/?i=topographic#@-41.8899962,174.0492437,z5
> feat(vector): Update latest lds data into topo map.

- config/tileset/aerial.json
- feat(aerial): add mackenzie_urban_2020_0.075m_RGB
- feat(aerial): add timaru_urban_2020_0.075m_RGB
> feat(aerial): add timaru_urban_2020_0.075m_RGB

- package.json
- yarn.lock
> build(deps): upgrade basemaps and remove yarn

- config/style/aerialhybrid.json
- config/style/basic.json
- config/style/topographic.json
some people want to zoom in past z24 and if everything turns off the map looks really weird
> fix(vector): remove max zoom 24 on all layers

- config/tileset/aerial.json
A cutline currently runs straight through the city - doesn't look great.
> feat(aerial): show Christchurch urban above rurals

- config/style/topographic.json
- config/style/topolite.json
- config/tileset/topographic.json
- Update the latest vector data up to date 2022-06-07
- Remove the river feat_type tagging in river layers
- Tagging class:drain and class:canal for drain and canal layers.
> feat(vector): Update the vector data and river tagging

- config/tileset/aerial.json
Imagery imported for waikato_urban_2021_0.1m_RGB, please use the following QA url once the aws job finished.
Individual Imagery NZTM2000Quad: https://basemaps.linz.govt.nz/?i=01G75YF8RQTNWDSTJ9618EGGSH&p=NZTM2000Quad&debug#@-37.538530,175.050941,z9
Individual Imagery WebMercatorQuad: https://basemaps.linz.govt.nz/?i=01G75YFYNRYPFF9H8P4CR4HDAJ&p=WebMercatorQuad&debug#@-37.527154,175.056152,z12
Tagged Aerial Map NZTM2000Quad: https://basemaps.linz.govt.nz/?p=NZTM2000Quad&i=aerial@pr-577#@-37.538530,175.050941,z9
Tagged Aerial Map WebMercatorQuad: https://basemaps.linz.govt.nz/?p=WebMercatorQuad&i=aerial@pr-577#@-37.527154,175.056152,z12
> feat(aerial): Config imagery waikato_urban_2021_0.1m_RGB into Aerial Map. BM-621

- README.md
- fix: convert fonts and glyphs back to /sprites /glyphs until next release
- docs: update readme to latest links
- docs: fix typo
> docs: update readme to latest links'

- config/tileset/aerial.json
…ai Valley areas
NZTM: https://basemaps.linz.govt.nz/?i=01GCQGF66GZ728Y9YSQ1TMTA1Q&p=NZTM2000Quad&debug#@-41.137640,173.242786,z9
Web Mercator: https://basemaps.linz.govt.nz/?i=01GCQGFTDSDCT82DMSES5A7ES1&debug=true#@-41.2040778,173.4691600,z11.5561
> feat(aerial): update Top of the South Flood latest imagery

- config/tileset/aerial.json
3857 - https://basemaps.linz.govt.nz/?i=01GD1JD8R7CM2X2YBET1AS2G98&p=WebMercatorQuad&debug#@-41.145570,173.232422,z12
2193 - https://basemaps.linz.govt.nz/?i=01GD1JCHCKQGK8FS2EP9PMNM7X&p=NZTM2000Quad&debug#@-41.148687,173.228252,z9
> feat(aerial): top of the south delivery for 2022-09-14

- .github/workflows/build.yml
- config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01F6P1CMT137757Y7M473TP4MG&p=NZTM2000Quad&debug#@-41.323791,173.564974,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-8eHR43MbmeV1hHecMBRhKWXX1maaGoUiRfPtbsPCww9W.json.gz&p=NZTM2000Quad&debug#@-41.323791,173.564974,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01ED82KF10YWWCA59936P87R9B&p=WebMercatorQuad&debug#@-41.343825,173.627930,z0) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-8eHR43MbmeV1hHecMBRhKWXX1maaGoUiRfPtbsPCww9W.json.gz&p=WebMercatorQuad&debug#@-41.343825,173.627930,z0)
- Zoom level updated
- Layer update [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01F66EEHWXVMK4B7E13AVZ8NE7&p=NZTM2000Quad&debug#@-43.990990,-176.513740,z9) -- …
> ci: Update the tagged url once uploaded hashed config

- config/tileset/topographic.json
QA: https://basemaps.linz.govt.nz/?s=topographic&i=topographic&config=s3://linz-basemaps/config/config-9rEtNjKf9BnMLdLYRh6Rosm2WAwuWa7nQHtWsMJowEdw.json.gz#@-41.8899962,174.0492437,z5
> feat(vector): Update the latest vector data 10 Oct 2022.

- .github/workflows/build.yml
- config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01GGE58D2ASW9PZW2GZGXFR7MP&p=NZTM2000Quad&debug#@-39.631967,175.617235,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-BWNyJWtZNsV9VTZypuWVMw3RrvFyKRjF2x8nZerqnfZ7.json.gz&p=NZTM2000Quad&debug#@-39.631967,175.617235,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01GGE59H8BW8NDQ76QYYWCYVJR&p=WebMercatorQuad&debug#@-39.639538,175.605469,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-BWNyJWtZNsV9VTZypuWVMw3RrvFyKRjF2x8nZerqnfZ7.json.gz&p=WebMercatorQuad&debug#@-39.639538,175.605469,z12)
- Zoom level updated. min zoom 13 -> 32
- Zoom level updated. min zoom 13 -> 32
- Zoom level updated. min zoom 13 -> 32
> feat(aerial): Config imagery Manawatu Whanganui 0.3m Rural into Aerial Map. BM-697

- config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?i=01GJ3WD5DCSRF0QN7JKN82GPCF&p=NZTM2000Quad&debug#@-46.483270,168.357650,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-BPNbsS4Bew5HF9EEzHYDpiH29uXwESMmByJuTkczH9qS.json.gz&p=NZTM2000Quad&debug#@-46.483270,168.357650,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?i=01GJ3WDN7PTMGZ14AH56GPX39G&p=WebMercatorQuad&debug#@-46.483265,168.354492,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps/config/config-BPNbsS4Bew5HF9EEzHYDpiH29uXwESMmByJuTkczH9qS.json.gz&p=WebMercatorQuad&debug#@-46.483265,168.354492,z12)
> feat(aerial): Config imagery invercargill_2022_0.05m into Aerial Map. BM-715

- config/tileset/aerial.json
- [NZTM200Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-E6wsEp3V4moFtQFSXwoLvuwLPMiW3JxuL14J4ZW7MjjJ.json.gz&i=tauranga-winter-2022-0.1m&p=NZTM2000Quad&debug#@-37.707514,176.238091,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-E6wsEp3V4moFtQFSXwoLvuwLPMiW3JxuL14J4ZW7MjjJ.json.gz&p=NZTM2000Quad&debug#@-37.707514,176.238091,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-E6wsEp3V4moFtQFSXwoLvuwLPMiW3JxuL14J4ZW7MjjJ.json.gz&i=tauranga-winter-2022-0.1m&p=WebMercatorQuad&debug#@-37.707726,176.242676,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-E6wsEp3V4moFtQFSXwoLvuwLPMiW3JxuL14J4ZW7MjjJ.json.gz&p=WebMer …
> feat(aerial): Config imagery tauranga_winter_2022_0.1m into Aerial Map. 

- config/tileset/aerial.json
Oops "fixed" the title but accidentally deleted the GSD.
> chore: add missing GSD in Tauranga Winter title

- config/style/positron.json
* [positron](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-6GwaBJq1EWyY5oZM3WZRAS9BuLEgxhph9vzGwxkwpQ9U.json.gz&i=topographic&s=positron&debug)
> config(style): Import Open map tiles positron style into LINZ basemaps

- config/tileset/aerial.json
- [NZTM2000Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-9XFXSQeYR5sDgot8uqa8V2SuWGP5f3ZePnGyVgjJAXgy.json.gz&i=canterbury-2022-0.3m&p=NZTM2000Quad&debug#@-43.404111,172.201927,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-9XFXSQeYR5sDgot8uqa8V2SuWGP5f3ZePnGyVgjJAXgy.json.gz&p=NZTM2000Quad&debug#@-43.404111,172.201927,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-9XFXSQeYR5sDgot8uqa8V2SuWGP5f3ZePnGyVgjJAXgy.json.gz&i=canterbury-2022-0.3m&p=WebMercatorQuad&debug#@-43.421009,172.166748,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-9XFXSQeYR5sDgot8uqa8V2SuWGP5f3ZePnGyVgjJAXgy.json.gz&p=WebMercatorQuad …
> feat(aerial): Config imagery canterbury_2022_0.3m into Aerial Map. 

- config/tileset/aerial.json
- Zoom level updated. min zoom 14 -> 32
- Zoom level updated. min zoom 14 -> 32
> feat(aerial): don't show old Waimakariri imagery

- config/tileset/aerial.json
- [NZTM2000Quad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-AwvCAwjsoAqKrJWpMa6PPbSDWxMQiqWGqFqxvcdPMWTD.json.gz&i=waikato-2021-2023-0.3m&p=NZTM2000Quad&debug#@-37.896360,175.624078,z9) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-AwvCAwjsoAqKrJWpMa6PPbSDWxMQiqWGqFqxvcdPMWTD.json.gz&p=NZTM2000Quad&debug#@-37.896360,175.624078,z9)
- [WebMercatorQuad](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-AwvCAwjsoAqKrJWpMa6PPbSDWxMQiqWGqFqxvcdPMWTD.json.gz&i=waikato-2021-2023-0.3m&p=WebMercatorQuad&debug#@-37.909534,175.643921,z12) -- [Aerial](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-AwvCAwjsoAqKrJWpMa6PPbSDWxMQiqWGqFqxvcdPMWTD.json.gz&p=WebMercator …
> feat(aerial): Config imagery waikato_2021-2023_0.3m into Aerial Map. 

- config/tileset/health.json
- config/tileset/reliefshade.json
- config/tileset/texture.relifshade.json
- config/tileset/textureshade.json
- config/tileset/topographic.json
* [topographic](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-5U4oLMXLoysvyBihjD9q6AZGfCDu5nk5wo9KghKrv31n.json.gz&i=topographic&s=topographic&debug)
* [topolite](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-5U4oLMXLoysvyBihjD9q6AZGfCDu5nk5wo9KghKrv31n.json.gz&i=topographic&s=topolite&debug)
* [aerialhybrid](https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-5U4oLMXLoysvyBihjD9q6AZGfCDu5nk5wo9KghKrv31n.json.gz&i=topographic&s=aerialhybrid&debug)
> config: Add the missing tileset titles as they are all required now.

- config/tileset/aerial.json
- Zoom level updated. min zoom 14 -> 32
> feat(aerial): don't show old Selwyn imagery

- config/tileset/event.cyclonegabrielle.json
https://basemaps.linz.govt.nz/?config=TmVmbYRQjL9T2JWgyaSie193b4D1qZnBD8hjaSqPFYSsEvEYYhaGYKrckRUqCd64HrB2JFYcNZVuL7NWFTXFrGc2A14saNFMavGBF6cMjnEcdNyqfEEdseoCo1qgLHP&i=cyclonegabrielle&p=NZTM2000Quad&debug=true#@-37.9770122,176.2754494,z4.4493
> feat(aerial): extend Sentinel coverage across the whole North Island

- .github/CODEOWNERS
Automatically assign @rclarkelinz to review changes to the aerial.json and event.*.json tilesets
> chore: add @rclarkelinz to CODEOWNERS

- config/tileset/aerial.json
feat(aerial): Add imagery southland-2023-0.25m to aerial config file.
> config(raster): add imagery  southland_2023_0.25m to aerial config file

- .github/pull_request_template.md
Changed to Motivation/Modification also used prettier for format the markdown file.
*If not applicable, provide explanation of why.*
> build: change to motivation

- .github/workflows/build.yml
- package-lock.json
- package.json
- scripts/bmc.sh
The deploy pipeline is currently taking 10+ minutes to complete this affects how quickly we can update the configuration of basemaps
reconfigure the deploy pipeline into multiple sub steps so it can be more efficient in deploying to nonprod/prod.
> ci: refactor build to improve build times

- .github/workflows/build.yml
production pipeline currently is disabled, enable it
enables the prod deployment pipeline
> ci: enable new deployment pipeline

- .github/workflows/build.yml
- scripts/bms.sh
Running basemaps smoke tests in the ci/cd.
Add another step in ci to run smoke test. 
> ci: Add basemaps smoke test in the ci/cd step. BM-1010

- .github/workflows/build.yml
The deployment import cmd missing a letter
> fix(ci): Fix the deployment import command.

- config/tileset/53382-nz-roads-addressing.json
[Cron Job](https://argo.linzaccess.com/workflows/argo/cron-vector-etl-roads-addressing-1715709600?tab=workflow&nodeId=cron-vector-etl-roads-addressing-1715709600-285662629&nodePanelView=inputs-outputs&uid=31793ee2-3935-47df-a26a-d19372c9eef7) failure on creating pull requests, Just manually creating it.
> feat(vector): Update the nz road address vector data.

- config/tileset/53382-nz-roads-addressing.json
create-pr is currently broken in the cron workflow.
_Why is this change being made? What implications or other considerations are there?_
> feat(vector): Update nz road addressing vector data.

- config/tileset/topographic.json
Create-pr for the vector etl is currently broken. Just update the id manually.
_Why is this change being made? What implications or other considerations are there?_
> feat(vector): Update the topographic data.

- config/tileset/aerial.json
- config/tileset/manawatu-whanganui/imagery/palmerston-north-2022-0.125m.json
_What does this change aim to achieve?_
_Why is this change being made? What implications or other considerations are there?_
> feat(raster): Import palmerston-north-2024-0.1m into aerial map.

- .github/pull_request_template.md
- config/tileset/elevation.json
We use NZTM/2193 for QA/QC it would be nice to have a basic 2193 elevation layer to work with
Adds a 2193 elevation layer off the source imagery
The PR builder will give demo links.
> config(elevation): add source NZTM 2193 layers in for basic 2193 elevation service

- config/tileset/aerial.json
> feat(raster): Import waimakariri_2024_0.25m into aerial config

- config/style/topographic.json
Add some sky style to the topograhpic map
> feat(vector): Add sky box into topographic map

- config/tileset/elevation.json
Some layers are fully covered by higher priority layers
- remove Waikato - Hamilton 2019
- remove orthland - Marsden Point 2016
- remove Canterbury - Amberley 2012
> config(elevation): remove elevation layers fully covered by another layer

- config/tileset/elevation.json
Elevation datasets were initially input by region, alphabetically
Re-ordered by date so that new datasets appear on top of old datasets
> feat(elevation): reorder by date

- config/tileset/elevation.json
Basemaps requests data from configured tilesets but these are entirely reflown so add no value.
Deleted reflown elevation surveys from the elevation.json
Will check resulting capture-areas
> feat(elevation): remove reflown areas from elevation.json

- config/tileset/elevation.json
> config(elevation): Add elevation canterbury_2020-2023_dem_1m to elevation LI-1553

- config/style/topographic.json
- config/style/topolite.json
> config(vector): add dynamic hillshade

- config/tileset/elevation.json
> feat(elevation): Update southland_2020-2023_dem_1m into elevation config.

- config/tileset/elevation.json
> feat(elevation): Import Waikato LiDAR 1m DEM (2024) into basemaps. LI-1551

- config/tileset/elevation.json
> feat(elevation): Import Bay of Plenty LiDAR 1m DEM (2024) into basemaps.  LI-1545

- config/tileset/topo-raster.json
Changing Zoom levels for 250k maps. From 11 to 12
> feat(raster): Update topo-raster.json zoom levels

- config/tileset/elevation.coastal.json
Adding coastal.elevation.json for 3D Coastal Mapping DEMs
Added a new tileset config
> feat: create elevation.coastal.json

- config/tileset/topo-raster.json
Many Topo maps have been updated. Process new data into our basemaps. 
https://www.linz.govt.nz/products-services/maps/new-zealand-topographic-maps/topo50-map-chooser/release-notes-update-history/march-2025-topo50-release-notes
> feat(raster): update topo raster to March 2025

- config/tileset/hillshade.igor.json
- config/tileset/hillshade.json
Re-import the DEM Hillshades. 4 new layers have been added
dem: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-mqvgz?tab=workflow&uid=e584fccb-df2b-49a1-8779-d527517aeb7b
dem igor: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-s7jqg?tab=summary&uid=890d284d-0497-46fb-b201-42afd19896c5
dem overview: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-nfzvt?tab=summary&uid=8df59be7-56f4-4700-970e-fe18d1633d8e
dem igor overview: https://argo.linzaccess.com/workflows/argo/basemaps-imagery-import-cogify-rmn2p?tab=summary&uid=db5145cc-9848-464b-bbc7-feb543391027
> feat: add new dem layers BM-1328

- config/tileset/elevation.coastal.dsm.json
Adds a new configuration file for DSM data outputs from the 3D Coastal Mapping Programme.
> feat(coastal): Add elevation.coastal.dsm.json config file
